/**
 * Cross-port fixture generator.
 *
 * Runs the TypeScript reference stamps on a battery of inputs and emits a
 * Rust source file containing the inputs and expected outputs.  Drop the
 * output into `rust/rust-e-sim-core/tests/parity_stamps.rs` and `cargo test` will
 * verify the Rust port matches the TS reference to within 1e-14.
 *
 * Run with:
 *   bun scripts/gen-stamp-parity.ts > rust/rust-e-sim-core/tests/parity_stamps.rs
 */

import { computeTransistorStamp } from '$lib/sim/transistor';
import { computeDiodeStamp } from '$lib/sim/diode';
import type { SimulationDiodeElement, SimulationTransistorElement } from '$lib/types';

interface DiodeCase {
    name: string;
    diode: SimulationDiodeElement;
    volts: number[];
    ai: number;
    ki: number;
    prevVolts?: number[];
}

interface TransistorCase {
    name: string;
    q: SimulationTransistorElement;
    volts: number[];
    bi: number;
    ci: number;
    ei: number;
    prevVolts?: number[];
}

// ── Diode cases ──────────────────────────────────────────────────────────

const dShockley = (is = 1e-14, n = 1): SimulationDiodeElement => ({
    type: 'diode', componentId: 'D', anodeNode: 0, cathodeNode: 1, is, n,
});
const dZener = (bv: number, is = 1e-14, n = 1): SimulationDiodeElement => ({
    type: 'diode', componentId: 'D', anodeNode: 0, cathodeNode: 1, is, n, bv,
});

const diodeCases: DiodeCase[] = [
    { name: 'reverse_bias',         diode: dShockley(),      volts: [-5,    0],   ai: 0, ki: 1 },
    { name: 'small_forward',        diode: dShockley(),      volts: [ 0.4,  0],   ai: 0, ki: 1 },
    { name: 'on_state',             diode: dShockley(),      volts: [ 0.7,  0],   ai: 0, ki: 1 },
    { name: 'high_n',               diode: dShockley(1e-14, 1.8), volts: [0.7, 0], ai: 0, ki: 1 },
    { name: 'grounded_anode_fwd',   diode: dShockley(),      volts: [ 0,   -0.6], ai: -1, ki: 1 },
    { name: 'grounded_cathode_fwd', diode: dShockley(),      volts: [ 0.6      ], ai:  0, ki: -1 },
    { name: 'zener_off',            diode: dZener(5.0),      volts: [ 0,    0  ], ai: 0, ki: 1 },
    { name: 'zener_breakdown',      diode: dZener(5.0),      volts: [-6,    0  ], ai: 0, ki: 1 },
    { name: 'pnjlim_engaged',       diode: dShockley(),      volts: [ 1,    0  ], ai: 0, ki: 1, prevVolts: [-1, 0] },
];

// ── Transistor cases ─────────────────────────────────────────────────────

const qNpn = (overrides: Partial<SimulationTransistorElement> = {}): SimulationTransistorElement => ({
    type: 'transistor', componentId: 'Q', polarity: 'npn',
    baseNode: 0, collectorNode: 1, emitterNode: 2,
    beta: 200, is: 6.734e-15, nf: 1, vaf: 74.03,
    cjeFarads: 0, cjcFarads: 0,
    ...overrides,
});
const qPnp = (overrides: Partial<SimulationTransistorElement> = {}): SimulationTransistorElement => ({
    type: 'transistor', componentId: 'Q', polarity: 'pnp',
    baseNode: 0, collectorNode: 1, emitterNode: 2,
    beta: 50, is: 1e-14, nf: 1, vaf: 50,
    cjeFarads: 0, cjcFarads: 0,
    ...overrides,
});

const transistorCases: TransistorCase[] = [
    { name: 'npn_off',                  q: qNpn(), volts: [0,    0,    0  ], bi: 0, ci: 1, ei: 2 },
    { name: 'npn_active',               q: qNpn(), volts: [0.65, 3.65, 0  ], bi: 0, ci: 1, ei: 2 },
    { name: 'npn_saturation',           q: qNpn(), volts: [0.7,  0.2,  0  ], bi: 0, ci: 1, ei: 2 },
    { name: 'pnp_active',               q: qPnp(), volts: [0,   -3,    0.65], bi: 0, ci: 1, ei: 2 },
    { name: 'npn_pnjlim',               q: qNpn(), volts: [1.5,  3,    0  ], bi: 0, ci: 1, ei: 2, prevVolts: [0, 3, 0] },
    { name: 'npn_transient_steady',     q: qNpn(), volts: [0.65, 3.65, 0  ], bi: 0, ci: 1, ei: 2, prevVolts: [0.65, 3.65, 0] },
    { name: 'npn_with_full_gp',         q: qNpn({ ikf: 0.05, ikr: 0.05, br: 5, var: 50, ise: 1e-12, nc: 2 }),
                                        volts: [0.65, 3.65, 0  ], bi: 0, ci: 1, ei: 2 },
    { name: 'npn_grounded_base',        q: qNpn(), volts: [3.65, 0   ], bi: -1, ci: 0, ei: 1 },
];

// ── Emit the Rust file ───────────────────────────────────────────────────

function rustFloat(n: number): string {
    if (Number.isNaN(n)) return 'f64::NAN';
    if (!Number.isFinite(n)) return n > 0 ? 'f64::INFINITY' : 'f64::NEG_INFINITY';
    // Use a long precision so the constant round-trips exactly.
    return n.toString().includes('.') || n.toString().includes('e')
        ? `${n.toString()}_f64`
        : `${n}.0_f64`;
}

function rustOpt(n: number | undefined): string {
    return n === undefined ? 'None' : `Some(${rustFloat(n)})`;
}

let out = '';
out += '// AUTOGENERATED by `bun scripts/gen-stamp-parity.ts` — do not edit by hand.\n';
out += '//\n';
out += '// Fixtures captured from the TypeScript reference implementation in\n';
out += '// src/lib/sim/transistor.ts and src/lib/sim/diode.ts.  Verifies that the\n';
out += '// Rust ports in rust-e-sim-core produce bit-for-bit (within 1e-14) identical\n';
out += '// stamps for the same inputs.\n\n';
out += 'use rust_e_sim_core::diode::compute_diode_stamp;\n';
out += 'use rust_e_sim_core::transistor::compute_transistor_stamp;\n';
out += 'use rust_e_sim_core::types::{Diode, Polarity, Transistor};\n\n';
out += 'const TOL: f64 = 1e-12;\n\n';

// Diode parity tests
for (const tc of diodeCases) {
    const r = computeDiodeStamp(
        tc.diode, new Float64Array(tc.volts), tc.ai, tc.ki,
        tc.prevVolts ? new Float64Array(tc.prevVolts) : undefined,
    );
    out += `#[test]\nfn diode_${tc.name}() {\n`;
    out += `    let d = Diode { is: ${rustFloat(tc.diode.is)}, n: ${rustFloat(tc.diode.n)}, `;
    out += `bv: ${rustOpt(tc.diode.bv)}, ibv: ${rustOpt(tc.diode.ibv)} };\n`;
    out += `    let volts: Vec<f64> = vec![${tc.volts.map(rustFloat).join(', ')}];\n`;
    if (tc.prevVolts) {
        out += `    let prev: Vec<f64>  = vec![${tc.prevVolts.map(rustFloat).join(', ')}];\n`;
        out += `    let stamp = compute_diode_stamp(&d, &volts, ${tc.ai}, ${tc.ki}, Some(&prev));\n`;
    } else {
        out += `    let stamp = compute_diode_stamp(&d, &volts, ${tc.ai}, ${tc.ki}, None);\n`;
    }
    out += `    assert!((stamp.gd  - ${rustFloat(r.gd)}).abs()  < TOL, "gd: {} vs {}", stamp.gd,  ${rustFloat(r.gd)});\n`;
    out += `    assert!((stamp.ieq - ${rustFloat(r.ieq)}).abs() < TOL, "ieq: {} vs {}", stamp.ieq, ${rustFloat(r.ieq)});\n`;
    out += `}\n\n`;
}

// Transistor parity tests
for (const tc of transistorCases) {
    const r = computeTransistorStamp(
        tc.q, new Float64Array(tc.volts), tc.bi, tc.ci, tc.ei,
        tc.prevVolts ? new Float64Array(tc.prevVolts) : undefined,
    );
    out += `#[test]\nfn transistor_${tc.name}() {\n`;
    out += `    let q = Transistor {\n`;
    out += `        polarity: Polarity::${tc.q.polarity === 'pnp' ? 'Pnp' : 'Npn'},\n`;
    out += `        beta: ${rustFloat(tc.q.beta)},\n`;
    out += `        br:   ${rustOpt(tc.q.br)},\n`;
    out += `        is:   ${rustFloat(tc.q.is)},\n`;
    out += `        nf:   ${rustFloat(tc.q.nf)},\n`;
    out += `        nr:   ${rustOpt(tc.q.nr)},\n`;
    out += `        vaf:  ${rustFloat(tc.q.vaf)},\n`;
    out += `        var_: ${rustOpt(tc.q.var)},\n`;
    out += `        ikf:  ${rustOpt(tc.q.ikf)},\n`;
    out += `        ikr:  ${rustOpt(tc.q.ikr)},\n`;
    out += `        ise:  ${rustOpt(tc.q.ise)},\n`;
    out += `        ne:   ${rustOpt(tc.q.ne)},\n`;
    out += `        isc:  ${rustOpt(tc.q.isc)},\n`;
    out += `        nc:   ${rustOpt(tc.q.nc)},\n`;
    out += `        cje_farads: ${rustFloat(tc.q.cjeFarads)},\n`;
    out += `        cjc_farads: ${rustFloat(tc.q.cjcFarads)},\n`;
    out += `        tf_seconds: ${rustOpt(tc.q.tfSeconds)},\n`;
    out += `        tr_seconds: ${rustOpt(tc.q.trSeconds)},\n`;
    out += `    };\n`;
    out += `    let volts: Vec<f64> = vec![${tc.volts.map(rustFloat).join(', ')}];\n`;
    if (tc.prevVolts) {
        out += `    let prev:  Vec<f64> = vec![${tc.prevVolts.map(rustFloat).join(', ')}];\n`;
        out += `    let s = compute_transistor_stamp(&q, &volts, ${tc.bi}, ${tc.ci}, ${tc.ei}, Some(&prev));\n`;
    } else {
        out += `    let s = compute_transistor_stamp(&q, &volts, ${tc.bi}, ${tc.ci}, ${tc.ei}, None);\n`;
    }
    const fields: [string, number][] = [
        ['g_be',   r.gBe], ['g_bc',  r.gBc],
        ['gm',     r.gm],  ['gmu',   r.gmu],
        ['gpi',    r.gpi], ['gmu_b', r.gmu_b],
        ['i_eq_b', r.iEqB],['i_eq_c', r.iEqC], ['i_eq_e', r.iEqE],
    ];
    for (const [f, v] of fields) {
        out += `    assert!((s.${f} - ${rustFloat(v)}).abs() < TOL, "${f}: {} vs {}", s.${f}, ${rustFloat(v)});\n`;
    }
    out += `}\n\n`;
}

console.log(out);
