// AUTOGENERATED by `bun scripts/gen-circuit-parity.ts` — do not edit by hand.
//
// Each test builds a small circuit in Rust identical to one driven through
// the TypeScript reference solver, runs the same number of backward-Euler
// steps with the same dt, and asserts node voltages match TS to within 1e-9
// at every sampled step.

use sim_core::compile::compile_netlist;
use sim_core::netlist::{Element, Netlist};
use sim_core::transient::{step_with_config, StepConfig, TransientState};

/// RC charging: 5V → 1kΩ → 1µF → ground, sampled across 5τ
#[test]
fn rc_charging() {
    const CASE_TOL: f64 = 1e-9_f64;
    let mut nl = Netlist::new(0);
    nl.push(Element::VoltageSource {
        id: "V1".into(),
        positive_node: 1, negative_node: 0,
        voltage: 5.0_f64,
    });
    nl.push(Element::Resistor {
        id: "R1".into(),
        a: 1, b: 2,
        resistance_ohms: 1000.0_f64,
    });
    nl.push(Element::Capacitor {
        id: "C1".into(),
        a: 2, b: 0,
        capacitance_farads: 0.000001_f64,
        initial_voltage: 0.0_f64,
    });

    let mut c = compile_netlist(&nl).unwrap();
    let mut s = TransientState::new(&c);
    let idx_1 = *c.node_index.get(&1).unwrap();
    let idx_2 = *c.node_index.get(&2).unwrap();

    // Run 1 step to reach step index 0.
    for _ in 0..1 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_1] - 1.0_f64).abs() < CASE_TOL,
        "step 0, node 1: {} vs 1.0_f64",
        s.node_volts[idx_1]);
    assert!((s.node_volts[idx_2] - 0.0049950049900149805_f64).abs() < CASE_TOL,
        "step 0, node 2: {} vs 0.0049950049900149805_f64",
        s.node_volts[idx_2]);

    // Run 100 steps to reach step index 100.
    for _ in 0..100 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_1] - 5.0_f64).abs() < CASE_TOL,
        "step 100, node 1: {} vs 5.0_f64",
        s.node_volts[idx_1]);
    assert!((s.node_volts[idx_2] - 0.4803315719794195_f64).abs() < CASE_TOL,
        "step 100, node 2: {} vs 0.4803315719794195_f64",
        s.node_volts[idx_2]);

    // Run 400 steps to reach step index 500.
    for _ in 0..400 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_1] - 4.999999999999999_f64).abs() < CASE_TOL,
        "step 500, node 1: {} vs 4.999999999999999_f64",
        s.node_volts[idx_1]);
    assert!((s.node_volts[idx_2] - 1.9703756189674309_f64).abs() < CASE_TOL,
        "step 500, node 2: {} vs 1.9703756189674309_f64",
        s.node_volts[idx_2]);

    // Run 500 steps to reach step index 1000.
    for _ in 0..500 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_1] - 4.999999999999999_f64).abs() < CASE_TOL,
        "step 1000, node 1: {} vs 4.999999999999999_f64",
        s.node_volts[idx_1]);
    assert!((s.node_volts[idx_2] - 3.162439183414692_f64).abs() < CASE_TOL,
        "step 1000, node 2: {} vs 3.162439183414692_f64",
        s.node_volts[idx_2]);

    // Run 1000 steps to reach step index 2000.
    for _ in 0..1000 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_1] - 4.999999999999999_f64).abs() < CASE_TOL,
        "step 2000, node 1: {} vs 4.999999999999999_f64",
        s.node_volts[idx_1]);
    assert!((s.node_volts[idx_2] - 4.32399689457768_f64).abs() < CASE_TOL,
        "step 2000, node 2: {} vs 4.32399689457768_f64",
        s.node_volts[idx_2]);

    // Run 2999 steps to reach step index 4999.
    for _ in 0..2999 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_1] - 5.0_f64).abs() < CASE_TOL,
        "step 4999, node 1: {} vs 5.0_f64",
        s.node_volts[idx_1]);
    assert!((s.node_volts[idx_2] - 4.966305498054551_f64).abs() < CASE_TOL,
        "step 4999, node 2: {} vs 4.966305498054551_f64",
        s.node_volts[idx_2]);

}

/// RC discharge: cap pre-charged to 3V, drains through 470Ω
#[test]
fn rc_discharging() {
    const CASE_TOL: f64 = 1e-9_f64;
    let mut nl = Netlist::new(0);
    nl.push(Element::Resistor {
        id: "R1".into(),
        a: 1, b: 0,
        resistance_ohms: 470.0_f64,
    });
    nl.push(Element::Capacitor {
        id: "C1".into(),
        a: 1, b: 0,
        capacitance_farads: 0.000001_f64,
        initial_voltage: 3.0_f64,
    });

    let mut c = compile_netlist(&nl).unwrap();
    let mut s = TransientState::new(&c);
    let idx_1 = *c.node_index.get(&1).unwrap();

    // Run 1 step to reach step index 0.
    for _ in 0..1 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_1] - 1.0_f64).abs() < CASE_TOL,
        "step 0, node 1: {} vs 1.0_f64",
        s.node_volts[idx_1]);

    // Run 100 steps to reach step index 100.
    for _ in 0..100 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_1] - 0.8109312123723869_f64).abs() < CASE_TOL,
        "step 100, node 1: {} vs 0.8109312123723869_f64",
        s.node_volts[idx_1]);

    // Run 400 steps to reach step index 500.
    for _ in 0..400 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_1] - 0.3462349933828757_f64).abs() < CASE_TOL,
        "step 500, node 1: {} vs 0.3462349933828757_f64",
        s.node_volts[idx_1]);

    // Run 1000 steps to reach step index 1500.
    for _ in 0..1000 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_1] - 0.04124186684488692_f64).abs() < CASE_TOL,
        "step 1500, node 1: {} vs 0.04124186684488692_f64",
        s.node_volts[idx_1]);

    // Run 1499 steps to reach step index 2999.
    for _ in 0..1499 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_1] - 0.0016990782606859773_f64).abs() < CASE_TOL,
        "step 2999, node 1: {} vs 0.0016990782606859773_f64",
        s.node_volts[idx_1]);

}

/// RLC underdamped: V step → R → L → C, oscillates
#[test]
fn rlc_underdamped() {
    const CASE_TOL: f64 = 1e-9_f64;
    let mut nl = Netlist::new(0);
    nl.push(Element::VoltageSource {
        id: "V1".into(),
        positive_node: 1, negative_node: 0,
        voltage: 5.0_f64,
    });
    nl.push(Element::Resistor {
        id: "R1".into(),
        a: 1, b: 2,
        resistance_ohms: 10.0_f64,
    });
    nl.push(Element::Inductor {
        id: "L1".into(),
        a: 2, b: 3,
        inductance_henry: 0.001_f64,
        saturation_current_a: None,
        coupling_group: None,
        coupling_polarity: 1,
    });
    nl.push(Element::Capacitor {
        id: "C1".into(),
        a: 3, b: 0,
        capacitance_farads: 1e-7_f64,
        initial_voltage: 0.0_f64,
    });

    let mut c = compile_netlist(&nl).unwrap();
    let mut s = TransientState::new(&c);
    let idx_2 = *c.node_index.get(&2).unwrap();
    let idx_3 = *c.node_index.get(&3).unwrap();

    // Run 1 step to reach step index 0.
    for _ in 0..1 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(5e-7_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 1.0_f64).abs() < CASE_TOL,
        "step 0, node 2: {} vs 1.0_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 0.012406947705448652_f64).abs() < CASE_TOL,
        "step 0, node 3: {} vs 0.012406947705448652_f64",
        s.node_volts[idx_3]);

    // Run 50 steps to reach step index 50.
    for _ in 0..50 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(5e-7_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 4.752652468523998_f64).abs() < CASE_TOL,
        "step 50, node 2: {} vs 4.752652468523998_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 8.51049094378981_f64).abs() < CASE_TOL,
        "step 50, node 3: {} vs 8.51049094378981_f64",
        s.node_volts[idx_3]);

    // Run 150 steps to reach step index 200.
    for _ in 0..150 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(5e-7_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 5.171914562537295_f64).abs() < CASE_TOL,
        "step 200, node 2: {} vs 5.171914562537295_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 7.573139910194898_f64).abs() < CASE_TOL,
        "step 200, node 3: {} vs 7.573139910194898_f64",
        s.node_volts[idx_3]);

    // Run 300 steps to reach step index 500.
    for _ in 0..300 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(5e-7_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 5.019254614297662_f64).abs() < CASE_TOL,
        "step 500, node 2: {} vs 5.019254614297662_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 3.5929965297097386_f64).abs() < CASE_TOL,
        "step 500, node 3: {} vs 3.5929965297097386_f64",
        s.node_volts[idx_3]);

    // Run 500 steps to reach step index 1000.
    for _ in 0..500 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(5e-7_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 5.012915839411735_f64).abs() < CASE_TOL,
        "step 1000, node 2: {} vs 5.012915839411735_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 4.6166987122378496_f64).abs() < CASE_TOL,
        "step 1000, node 3: {} vs 4.6166987122378496_f64",
        s.node_volts[idx_3]);

    // Run 1000 steps to reach step index 2000.
    for _ in 0..1000 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(5e-7_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 5.0021551957820884_f64).abs() < CASE_TOL,
        "step 2000, node 2: {} vs 5.0021551957820884_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 4.974943518110688_f64).abs() < CASE_TOL,
        "step 2000, node 3: {} vs 4.974943518110688_f64",
        s.node_volts[idx_3]);

    // Run 1999 steps to reach step index 3999.
    for _ in 0..1999 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(5e-7_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 5.000022913676321_f64).abs() < CASE_TOL,
        "step 3999, node 2: {} vs 5.000022913676321_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 4.999989944965651_f64).abs() < CASE_TOL,
        "step 3999, node 3: {} vs 4.999989944965651_f64",
        s.node_volts[idx_3]);

}

/// RL step response: L current builds up to V/R
#[test]
fn rl_step() {
    const CASE_TOL: f64 = 1e-9_f64;
    let mut nl = Netlist::new(0);
    nl.push(Element::VoltageSource {
        id: "V1".into(),
        positive_node: 1, negative_node: 0,
        voltage: 1.0_f64,
    });
    nl.push(Element::Resistor {
        id: "R1".into(),
        a: 1, b: 2,
        resistance_ohms: 100.0_f64,
    });
    nl.push(Element::Inductor {
        id: "L1".into(),
        a: 2, b: 0,
        inductance_henry: 0.001_f64,
        saturation_current_a: None,
        coupling_group: None,
        coupling_polarity: 1,
    });

    let mut c = compile_netlist(&nl).unwrap();
    let mut s = TransientState::new(&c);
    let idx_2 = *c.node_index.get(&2).unwrap();

    // Run 1 step to reach step index 0.
    for _ in 0..1 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 0.9090908264057047_f64).abs() < CASE_TOL,
        "step 0, node 2: {} vs 0.9090908264057047_f64",
        s.node_volts[idx_2]);

    // Run 100 steps to reach step index 100.
    for _ in 0..100 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 0.00003992292810554588_f64).abs() < CASE_TOL,
        "step 100, node 2: {} vs 0.00003992292810554588_f64",
        s.node_volts[idx_2]);

    // Run 400 steps to reach step index 500.
    for _ in 0..400 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 0.0_f64).abs() < CASE_TOL,
        "step 500, node 2: {} vs 0.0_f64",
        s.node_volts[idx_2]);

    // Run 1000 steps to reach step index 1500.
    for _ in 0..1000 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 0.0_f64).abs() < CASE_TOL,
        "step 1500, node 2: {} vs 0.0_f64",
        s.node_volts[idx_2]);

    // Run 3499 steps to reach step index 4999.
    for _ in 0..3499 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 0.0_f64).abs() < CASE_TOL,
        "step 4999, node 2: {} vs 0.0_f64",
        s.node_volts[idx_2]);

}

/// Two coupled inductors (k=0.5) with primary V step, secondary into load
#[test]
fn transformer_step_response() {
    const CASE_TOL: f64 = 1e-9_f64;
    let mut nl = Netlist::new(0);
    nl.push(Element::VoltageSource {
        id: "V1".into(),
        positive_node: 1, negative_node: 0,
        voltage: 1.0_f64,
    });
    nl.push(Element::Resistor {
        id: "Rsrc".into(),
        a: 1, b: 2,
        resistance_ohms: 1.0_f64,
    });
    nl.push(Element::Inductor {
        id: "L1".into(),
        a: 2, b: 0,
        inductance_henry: 0.01_f64,
        saturation_current_a: None,
        coupling_group: Some("core".into()),
        coupling_polarity: 1,
    });
    nl.push(Element::Inductor {
        id: "L2".into(),
        a: 3, b: 0,
        inductance_henry: 0.01_f64,
        saturation_current_a: None,
        coupling_group: Some("core".into()),
        coupling_polarity: 1,
    });
    nl.push(Element::Resistor {
        id: "Rload".into(),
        a: 3, b: 0,
        resistance_ohms: 100.0_f64,
    });
    nl.push(Element::Coupling {
        id: "K".into(),
        coupling_group: "core".into(),
        k: 0.5_f64,
    });

    let mut c = compile_netlist(&nl).unwrap();
    let mut s = TransientState::new(&c);
    let idx_2 = *c.node_index.get(&2).unwrap();
    let idx_3 = *c.node_index.get(&3).unwrap();

    // Run 1 step to reach step index 0.
    for _ in 0..1 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 0.9998671219274581_f64).abs() < CASE_TOL,
        "step 0, node 2: {} vs 0.9998671219274581_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 0.006578072521387002_f64).abs() < CASE_TOL,
        "step 0, node 3: {} vs 0.006578072521387002_f64",
        s.node_volts[idx_3]);

    // Run 50 steps to reach step index 50.
    for _ in 0..50 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 0.9936875560315637_f64).abs() < CASE_TOL,
        "step 50, node 2: {} vs 0.9936875560315637_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 0.24578368152662108_f64).abs() < CASE_TOL,
        "step 50, node 3: {} vs 0.24578368152662108_f64",
        s.node_volts[idx_3]);

    // Run 150 steps to reach step index 200.
    for _ in 0..150 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 0.9778413935518252_f64).abs() < CASE_TOL,
        "step 200, node 2: {} vs 0.9778413935518252_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 0.45829925729051757_f64).abs() < CASE_TOL,
        "step 200, node 3: {} vs 0.45829925729051757_f64",
        s.node_volts[idx_3]);

    // Run 300 steps to reach step index 500.
    for _ in 0..300 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 0.9488491602551292_f64).abs() < CASE_TOL,
        "step 500, node 2: {} vs 0.9488491602551292_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 0.4773786774637643_f64).abs() < CASE_TOL,
        "step 500, node 3: {} vs 0.4773786774637643_f64",
        s.node_volts[idx_3]);

    // Run 500 steps to reach step index 1000.
    for _ in 0..500 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 0.902683665567546_f64).abs() < CASE_TOL,
        "step 1000, node 2: {} vs 0.902683665567546_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 0.4547430648616228_f64).abs() < CASE_TOL,
        "step 1000, node 3: {} vs 0.4547430648616228_f64",
        s.node_volts[idx_3]);

    // Run 999 steps to reach step index 1999.
    for _ in 0..999 {
        step_with_config(&mut c, &mut s, StepConfig::bdf2(0.000001_f64)).unwrap();
    }
    assert!((s.node_volts[idx_2] - 0.8170687061461942_f64).abs() < CASE_TOL,
        "step 1999, node 2: {} vs 0.8170687061461942_f64",
        s.node_volts[idx_2]);
    assert!((s.node_volts[idx_3] - 0.4116136938629548_f64).abs() < CASE_TOL,
        "step 1999, node 3: {} vs 0.4116136938629548_f64",
        s.node_volts[idx_3]);

}


