// AUTOGENERATED by `bun scripts/gen-stamp-parity.ts` — do not edit by hand.
//
// Fixtures captured from the TypeScript reference implementation in
// src/lib/sim/transistor.ts and src/lib/sim/diode.ts.  Verifies that the
// Rust ports in sim-core produce bit-for-bit (within 1e-14) identical
// stamps for the same inputs.

use sim_core::diode::compute_diode_stamp;
use sim_core::transistor::compute_transistor_stamp;
use sim_core::types::{Diode, Polarity, Transistor};

const TOL: f64 = 1e-12;

#[test]
fn diode_reverse_bias() {
    let d = Diode { is: 1e-14_f64, n: 1.0_f64, bv: None, ibv: None };
    let volts: Vec<f64> = vec![-5.0_f64, 0.0_f64];
    let stamp = compute_diode_stamp(&d, &volts, 0, 1, None);
    assert!((stamp.gd  - 1e-12_f64).abs()  < TOL, "gd: {} vs {}", stamp.gd,  1e-12_f64);
    assert!((stamp.ieq - 4.9899999999999995e-12_f64).abs() < TOL, "ieq: {} vs {}", stamp.ieq, 4.9899999999999995e-12_f64);
}

#[test]
fn diode_small_forward() {
    let d = Diode { is: 1e-14_f64, n: 1.0_f64, bv: None, ibv: None };
    let volts: Vec<f64> = vec![0.4_f64, 0.0_f64];
    let stamp = compute_diode_stamp(&d, &volts, 0, 1, None);
    assert!((stamp.gd  - 0.0000020312507745010864_f64).abs()  < TOL, "gd: {} vs {}", stamp.gd,  0.0000020312507745010864_f64);
    assert!((stamp.ieq - -7.599924872795815e-7_f64).abs() < TOL, "ieq: {} vs {}", stamp.ieq, -7.599924872795815e-7_f64);
}

#[test]
fn diode_on_state() {
    let d = Diode { is: 1e-14_f64, n: 1.0_f64, bv: None, ibv: None };
    let volts: Vec<f64> = vec![0.7_f64, 0.0_f64];
    let stamp = compute_diode_stamp(&d, &volts, 0, 1, None);
    assert!((stamp.gd  - 0.2228084269206605_f64).abs()  < TOL, "gd: {} vs {}", stamp.gd,  0.2228084269206605_f64);
    assert!((stamp.ieq - -0.15020630100857324_f64).abs() < TOL, "ieq: {} vs {}", stamp.ieq, -0.15020630100857324_f64);
}

#[test]
fn diode_high_n() {
    let d = Diode { is: 1e-14_f64, n: 1.8_f64, bv: None, ibv: None };
    let volts: Vec<f64> = vec![0.7_f64, 0.0_f64];
    let stamp = compute_diode_stamp(&d, &volts, 0, 1, None);
    assert!((stamp.gd  - 7.342063687292998e-7_f64).abs()  < TOL, "gd: {} vs {}", stamp.gd,  7.342063687292998e-7_f64);
    assert!((stamp.ieq - -4.797818457735355e-7_f64).abs() < TOL, "ieq: {} vs {}", stamp.ieq, -4.797818457735355e-7_f64);
}

#[test]
fn diode_grounded_anode_fwd() {
    let d = Diode { is: 1e-14_f64, n: 1.0_f64, bv: None, ibv: None };
    let volts: Vec<f64> = vec![0.0_f64, -0.6_f64];
    let stamp = compute_diode_stamp(&d, &volts, -1, 1, None);
    assert!((stamp.gd  - 0.00465452738245195_f64).abs()  < TOL, "gd: {} vs {}", stamp.gd,  0.00465452738245195_f64);
    assert!((stamp.ieq - -0.0026723968966447867_f64).abs() < TOL, "ieq: {} vs {}", stamp.ieq, -0.0026723968966447867_f64);
}

#[test]
fn diode_grounded_cathode_fwd() {
    let d = Diode { is: 1e-14_f64, n: 1.0_f64, bv: None, ibv: None };
    let volts: Vec<f64> = vec![0.6_f64];
    let stamp = compute_diode_stamp(&d, &volts, 0, -1, None);
    assert!((stamp.gd  - 0.00465452738245195_f64).abs()  < TOL, "gd: {} vs {}", stamp.gd,  0.00465452738245195_f64);
    assert!((stamp.ieq - -0.0026723968966447867_f64).abs() < TOL, "ieq: {} vs {}", stamp.ieq, -0.0026723968966447867_f64);
}

#[test]
fn diode_zener_off() {
    let d = Diode { is: 1e-14_f64, n: 1.0_f64, bv: Some(5.0_f64), ibv: None };
    let volts: Vec<f64> = vec![0.0_f64, 0.0_f64];
    let stamp = compute_diode_stamp(&d, &volts, 0, 1, None);
    assert!((stamp.gd  - 1e-12_f64).abs()  < TOL, "gd: {} vs {}", stamp.gd,  1e-12_f64);
    assert!((stamp.ieq - -4.248354255291589e-21_f64).abs() < TOL, "ieq: {} vs {}", stamp.ieq, -4.248354255291589e-21_f64);
}

#[test]
fn diode_zener_breakdown() {
    let d = Diode { is: 1e-14_f64, n: 1.0_f64, bv: Some(5.0_f64), ibv: None };
    let volts: Vec<f64> = vec![-6.0_f64, 0.0_f64];
    let stamp = compute_diode_stamp(&d, &volts, 0, 1, None);
    assert!((stamp.gd  - 2443991442615116.0_f64).abs()  < TOL, "gd: {} vs {}", stamp.gd,  2443991442615116.0_f64);
    assert!((stamp.ieq - 14600771476899096.0_f64).abs() < TOL, "ieq: {} vs {}", stamp.ieq, 14600771476899096.0_f64);
}

#[test]
fn diode_pnjlim_engaged() {
    let d = Diode { is: 1e-14_f64, n: 1.0_f64, bv: None, ibv: None };
    let volts: Vec<f64> = vec![1.0_f64, 0.0_f64];
    let prev: Vec<f64>  = vec![-1.0_f64, 0.0_f64];
    let stamp = compute_diode_stamp(&d, &volts, 0, 1, Some(&prev));
    assert!((stamp.gd  - 1.4965075255622195e-11_f64).abs()  < TOL, "gd: {} vs {}", stamp.gd,  1.4965075255622195e-11_f64);
    assert!((stamp.ieq - -1.0372513261229013e-12_f64).abs() < TOL, "ieq: {} vs {}", stamp.ieq, -1.0372513261229013e-12_f64);
}

#[test]
fn transistor_npn_off() {
    let q = Transistor {
        polarity: Polarity::Npn,
        beta: 200.0_f64,
        br:   None,
        is:   6.734e-15_f64,
        nf:   1.0_f64,
        nr:   None,
        vaf:  74.03_f64,
        var_: None,
        ikf:  None,
        ikr:  None,
        ise:  None,
        ne:   None,
        isc:  None,
        nc:   None,
        cje_farads: 0.0_f64,
        cjc_farads: 0.0_f64,
        tf_seconds: None,
        tr_seconds: None,
    };
    let volts: Vec<f64> = vec![0.0_f64, 0.0_f64, 0.0_f64];
    let s = compute_transistor_stamp(&q, &volts, 0, 1, 2, None);
    assert!((s.g_be - 1e-12_f64).abs() < TOL, "g_be: {} vs {}", s.g_be, 1e-12_f64);
    assert!((s.g_bc - 1e-12_f64).abs() < TOL, "g_bc: {} vs {}", s.g_bc, 1e-12_f64);
    assert!((s.gm - 1e-12_f64).abs() < TOL, "gm: {} vs {}", s.gm, 1e-12_f64);
    assert!((s.gmu - -6.51257253384913e-13_f64).abs() < TOL, "gmu: {} vs {}", s.gmu, -6.51257253384913e-13_f64);
    assert!((s.gpi - 1e-12_f64).abs() < TOL, "gpi: {} vs {}", s.gpi, 1e-12_f64);
    assert!((s.gmu_b - 1e-12_f64).abs() < TOL, "gmu_b: {} vs {}", s.gmu_b, 1e-12_f64);
    assert!((s.i_eq_b - 0.0_f64).abs() < TOL, "i_eq_b: {} vs {}", s.i_eq_b, 0.0_f64);
    assert!((s.i_eq_c - 0.0_f64).abs() < TOL, "i_eq_c: {} vs {}", s.i_eq_c, 0.0_f64);
    assert!((s.i_eq_e - 0.0_f64).abs() < TOL, "i_eq_e: {} vs {}", s.i_eq_e, 0.0_f64);
}

#[test]
fn transistor_npn_active() {
    let q = Transistor {
        polarity: Polarity::Npn,
        beta: 200.0_f64,
        br:   None,
        is:   6.734e-15_f64,
        nf:   1.0_f64,
        nr:   None,
        vaf:  74.03_f64,
        var_: None,
        ikf:  None,
        ikr:  None,
        ise:  None,
        ne:   None,
        isc:  None,
        nc:   None,
        cje_farads: 0.0_f64,
        cjc_farads: 0.0_f64,
        tf_seconds: None,
        tr_seconds: None,
    };
    let volts: Vec<f64> = vec![0.65_f64, 3.65_f64, 0.0_f64];
    let s = compute_transistor_stamp(&q, &volts, 0, 1, 2, None);
    assert!((s.g_be - 0.00010844587100040088_f64).abs() < TOL, "g_be: {} vs {}", s.g_be, 0.00010844587100040088_f64);
    assert!((s.g_bc - 1e-12_f64).abs() < TOL, "g_bc: {} vs {}", s.g_bc, 1e-12_f64);
    assert!((s.gm - 0.022418099600883146_f64).abs() < TOL, "gm: {} vs {}", s.gm, 0.022418099600883146_f64);
    assert!((s.gmu - -0.0000075723296333643255_f64).abs() < TOL, "gmu: {} vs {}", s.gmu, -0.0000075723296333643255_f64);
    assert!((s.gpi - 0.00010844587100040088_f64).abs() < TOL, "gpi: {} vs {}", s.gpi, 0.00010844587100040088_f64);
    assert!((s.gmu_b - 1e-12_f64).abs() < TOL, "gmu_b: {} vs {}", s.gmu_b, 1e-12_f64);
    assert!((s.i_eq_b - 0.0_f64).abs() < TOL, "i_eq_b: {} vs {}", s.i_eq_b, 0.0_f64);
    assert!((s.i_eq_c - 0.0_f64).abs() < TOL, "i_eq_c: {} vs {}", s.i_eq_c, 0.0_f64);
    assert!((s.i_eq_e - 0.0_f64).abs() < TOL, "i_eq_e: {} vs {}", s.i_eq_e, 0.0_f64);
}

#[test]
fn transistor_npn_saturation() {
    let q = Transistor {
        polarity: Polarity::Npn,
        beta: 200.0_f64,
        br:   None,
        is:   6.734e-15_f64,
        nf:   1.0_f64,
        nr:   None,
        vaf:  74.03_f64,
        var_: None,
        ikf:  None,
        ikr:  None,
        ise:  None,
        ne:   None,
        isc:  None,
        nc:   None,
        cje_farads: 0.0_f64,
        cjc_farads: 0.0_f64,
        tf_seconds: None,
        tr_seconds: None,
    };
    let volts: Vec<f64> = vec![0.7_f64, 0.2_f64, 0.0_f64];
    let s = compute_transistor_stamp(&q, &volts, 0, 1, 2, None);
    assert!((s.g_be - 0.0007502560842753425_f64).abs() < TOL, "g_be: {} vs {}", s.g_be, 0.0007502560842753425_f64);
    assert!((s.g_bc - 0.00006547965390025224_f64).abs() < TOL, "g_bc: {} vs {}", s.g_bc, 0.00006547965390025224_f64);
    assert!((s.gm - 0.1_f64).abs() < TOL, "gm: {} vs {}", s.gm, 0.1_f64);
    assert!((s.gmu - -0.00018242489983576416_f64).abs() < TOL, "gmu: {} vs {}", s.gmu, -0.00018242489983576416_f64);
    assert!((s.gpi - 0.0007502560842753425_f64).abs() < TOL, "gpi: {} vs {}", s.gpi, 0.0007502560842753425_f64);
    assert!((s.gmu_b - 0.00006547965390025224_f64).abs() < TOL, "gmu_b: {} vs {}", s.gmu_b, 0.00006547965390025224_f64);
    assert!((s.i_eq_b - 0.0_f64).abs() < TOL, "i_eq_b: {} vs {}", s.i_eq_b, 0.0_f64);
    assert!((s.i_eq_c - 0.0_f64).abs() < TOL, "i_eq_c: {} vs {}", s.i_eq_c, 0.0_f64);
    assert!((s.i_eq_e - 0.0_f64).abs() < TOL, "i_eq_e: {} vs {}", s.i_eq_e, 0.0_f64);
}

#[test]
fn transistor_pnp_active() {
    let q = Transistor {
        polarity: Polarity::Pnp,
        beta: 50.0_f64,
        br:   None,
        is:   1e-14_f64,
        nf:   1.0_f64,
        nr:   None,
        vaf:  50.0_f64,
        var_: None,
        ikf:  None,
        ikr:  None,
        ise:  None,
        ne:   None,
        isc:  None,
        nc:   None,
        cje_farads: 0.0_f64,
        cjc_farads: 0.0_f64,
        tf_seconds: None,
        tr_seconds: None,
    };
    let volts: Vec<f64> = vec![0.0_f64, -3.0_f64, 0.65_f64];
    let s = compute_transistor_stamp(&q, &volts, 0, 1, 2, None);
    assert!((s.g_be - 0.0006441691179114991_f64).abs() < TOL, "g_be: {} vs {}", s.g_be, 0.0006441691179114991_f64);
    assert!((s.g_bc - 1e-12_f64).abs() < TOL, "g_bc: {} vs {}", s.g_bc, 1e-12_f64);
    assert!((s.gm - 0.033918103721918495_f64).abs() < TOL, "gm: {} vs {}", s.gm, 0.033918103721918495_f64);
    assert!((s.gmu - -0.00001664922966313658_f64).abs() < TOL, "gmu: {} vs {}", s.gmu, -0.00001664922966313658_f64);
    assert!((s.gpi - 0.0006441691179114991_f64).abs() < TOL, "gpi: {} vs {}", s.gpi, 0.0006441691179114991_f64);
    assert!((s.gmu_b - 1e-12_f64).abs() < TOL, "gmu_b: {} vs {}", s.gmu_b, 1e-12_f64);
    assert!((s.i_eq_b - 0.0_f64).abs() < TOL, "i_eq_b: {} vs {}", s.i_eq_b, 0.0_f64);
    assert!((s.i_eq_c - 0.0_f64).abs() < TOL, "i_eq_c: {} vs {}", s.i_eq_c, 0.0_f64);
    assert!((s.i_eq_e - 0.0_f64).abs() < TOL, "i_eq_e: {} vs {}", s.i_eq_e, 0.0_f64);
}

#[test]
fn transistor_npn_pnjlim() {
    let q = Transistor {
        polarity: Polarity::Npn,
        beta: 200.0_f64,
        br:   None,
        is:   6.734e-15_f64,
        nf:   1.0_f64,
        nr:   None,
        vaf:  74.03_f64,
        var_: None,
        ikf:  None,
        ikr:  None,
        ise:  None,
        ne:   None,
        isc:  None,
        nc:   None,
        cje_farads: 0.0_f64,
        cjc_farads: 0.0_f64,
        tf_seconds: None,
        tr_seconds: None,
    };
    let volts: Vec<f64> = vec![1.5_f64, 3.0_f64, 0.0_f64];
    let prev:  Vec<f64> = vec![0.0_f64, 3.0_f64, 0.0_f64];
    let s = compute_transistor_stamp(&q, &volts, 0, 1, 2, Some(&prev));
    assert!((s.g_be - 1e-12_f64).abs() < TOL, "g_be: {} vs {}", s.g_be, 1e-12_f64);
    assert!((s.g_bc - 1e-12_f64).abs() < TOL, "g_bc: {} vs {}", s.g_bc, 1e-12_f64);
    assert!((s.gm - 1.540273253642415e-11_f64).abs() < TOL, "gm: {} vs {}", s.gm, 1.540273253642415e-11_f64);
    assert!((s.gmu - -5.278324355441953e-15_f64).abs() < TOL, "gmu: {} vs {}", s.gmu, -5.278324355441953e-15_f64);
    assert!((s.gpi - 1e-12_f64).abs() < TOL, "gpi: {} vs {}", s.gpi, 1e-12_f64);
    assert!((s.gmu_b - 1e-12_f64).abs() < TOL, "gmu_b: {} vs {}", s.gmu_b, 1e-12_f64);
    assert!((s.i_eq_b - 1.383948571511891e-12_f64).abs() < TOL, "i_eq_b: {} vs {}", s.i_eq_b, 1.383948571511891e-12_f64);
    assert!((s.i_eq_c - -1.2130822639233914e-12_f64).abs() < TOL, "i_eq_c: {} vs {}", s.i_eq_c, -1.2130822639233914e-12_f64);
    assert!((s.i_eq_e - -1.7086630758849955e-13_f64).abs() < TOL, "i_eq_e: {} vs {}", s.i_eq_e, -1.7086630758849955e-13_f64);
}

#[test]
fn transistor_npn_transient_steady() {
    let q = Transistor {
        polarity: Polarity::Npn,
        beta: 200.0_f64,
        br:   None,
        is:   6.734e-15_f64,
        nf:   1.0_f64,
        nr:   None,
        vaf:  74.03_f64,
        var_: None,
        ikf:  None,
        ikr:  None,
        ise:  None,
        ne:   None,
        isc:  None,
        nc:   None,
        cje_farads: 0.0_f64,
        cjc_farads: 0.0_f64,
        tf_seconds: None,
        tr_seconds: None,
    };
    let volts: Vec<f64> = vec![0.65_f64, 3.65_f64, 0.0_f64];
    let prev:  Vec<f64> = vec![0.65_f64, 3.65_f64, 0.0_f64];
    let s = compute_transistor_stamp(&q, &volts, 0, 1, 2, Some(&prev));
    assert!((s.g_be - 0.00010844587100040088_f64).abs() < TOL, "g_be: {} vs {}", s.g_be, 0.00010844587100040088_f64);
    assert!((s.g_bc - 1e-12_f64).abs() < TOL, "g_bc: {} vs {}", s.g_bc, 1e-12_f64);
    assert!((s.gm - 0.022418099600883146_f64).abs() < TOL, "gm: {} vs {}", s.gm, 0.022418099600883146_f64);
    assert!((s.gmu - -0.0000075723296333643255_f64).abs() < TOL, "gmu: {} vs {}", s.gmu, -0.0000075723296333643255_f64);
    assert!((s.gpi - 0.00010844587100040088_f64).abs() < TOL, "gpi: {} vs {}", s.gpi, 0.00010844587100040088_f64);
    assert!((s.gmu_b - 1e-12_f64).abs() < TOL, "gmu_b: {} vs {}", s.gmu_b, 1e-12_f64);
    assert!((s.i_eq_b - -0.00006768627342265105_f64).abs() < TOL, "i_eq_b: {} vs {}", s.i_eq_b, -0.00006768627342265105_f64);
    assert!((s.i_eq_c - -0.014014828944960544_f64).abs() < TOL, "i_eq_c: {} vs {}", s.i_eq_c, -0.014014828944960544_f64);
    assert!((s.i_eq_e - 0.014082515218383196_f64).abs() < TOL, "i_eq_e: {} vs {}", s.i_eq_e, 0.014082515218383196_f64);
}

#[test]
fn transistor_npn_with_full_gp() {
    let q = Transistor {
        polarity: Polarity::Npn,
        beta: 200.0_f64,
        br:   Some(5.0_f64),
        is:   6.734e-15_f64,
        nf:   1.0_f64,
        nr:   None,
        vaf:  74.03_f64,
        var_: Some(50.0_f64),
        ikf:  Some(0.05_f64),
        ikr:  Some(0.05_f64),
        ise:  Some(1e-12_f64),
        ne:   None,
        isc:  None,
        nc:   Some(2.0_f64),
        cje_farads: 0.0_f64,
        cjc_farads: 0.0_f64,
        tf_seconds: None,
        tr_seconds: None,
    };
    let volts: Vec<f64> = vec![0.65_f64, 3.65_f64, 0.0_f64];
    let s = compute_transistor_stamp(&q, &volts, 0, 1, 2, None);
    assert!((s.g_be - 0.0006001188442119719_f64).abs() < TOL, "g_be: {} vs {}", s.g_be, 0.0006001188442119719_f64);
    assert!((s.g_bc - 1e-12_f64).abs() < TOL, "g_bc: {} vs {}", s.g_bc, 1e-12_f64);
    assert!((s.gm - 0.021788209792523792_f64).abs() < TOL, "gm: {} vs {}", s.gm, 0.021788209792523792_f64);
    assert!((s.gmu - -0.00000748928371139383_f64).abs() < TOL, "gmu: {} vs {}", s.gmu, -0.00000748928371139383_f64);
    assert!((s.gpi - 0.0006001188442119719_f64).abs() < TOL, "gpi: {} vs {}", s.gpi, 0.0006001188442119719_f64);
    assert!((s.gmu_b - 1e-12_f64).abs() < TOL, "gmu_b: {} vs {}", s.gmu_b, 1e-12_f64);
    assert!((s.i_eq_b - 0.0_f64).abs() < TOL, "i_eq_b: {} vs {}", s.i_eq_b, 0.0_f64);
    assert!((s.i_eq_c - 0.0_f64).abs() < TOL, "i_eq_c: {} vs {}", s.i_eq_c, 0.0_f64);
    assert!((s.i_eq_e - 0.0_f64).abs() < TOL, "i_eq_e: {} vs {}", s.i_eq_e, 0.0_f64);
}

#[test]
fn transistor_npn_grounded_base() {
    let q = Transistor {
        polarity: Polarity::Npn,
        beta: 200.0_f64,
        br:   None,
        is:   6.734e-15_f64,
        nf:   1.0_f64,
        nr:   None,
        vaf:  74.03_f64,
        var_: None,
        ikf:  None,
        ikr:  None,
        ise:  None,
        ne:   None,
        isc:  None,
        nc:   None,
        cje_farads: 0.0_f64,
        cjc_farads: 0.0_f64,
        tf_seconds: None,
        tr_seconds: None,
    };
    let volts: Vec<f64> = vec![3.65_f64, 0.0_f64];
    let s = compute_transistor_stamp(&q, &volts, -1, 0, 1, None);
    assert!((s.g_be - 1e-12_f64).abs() < TOL, "g_be: {} vs {}", s.g_be, 1e-12_f64);
    assert!((s.g_bc - 1e-12_f64).abs() < TOL, "g_bc: {} vs {}", s.g_bc, 1e-12_f64);
    assert!((s.gm - 1e-12_f64).abs() < TOL, "gm: {} vs {}", s.gm, 1e-12_f64);
    assert!((s.gmu - -9.096312305822246e-17_f64).abs() < TOL, "gmu: {} vs {}", s.gmu, -9.096312305822246e-17_f64);
    assert!((s.gpi - 1e-12_f64).abs() < TOL, "gpi: {} vs {}", s.gpi, 1e-12_f64);
    assert!((s.gmu_b - 1e-12_f64).abs() < TOL, "gmu_b: {} vs {}", s.gmu_b, 1e-12_f64);
    assert!((s.i_eq_b - 0.0_f64).abs() < TOL, "i_eq_b: {} vs {}", s.i_eq_b, 0.0_f64);
    assert!((s.i_eq_c - 0.0_f64).abs() < TOL, "i_eq_c: {} vs {}", s.i_eq_c, 0.0_f64);
    assert!((s.i_eq_e - 0.0_f64).abs() < TOL, "i_eq_e: {} vs {}", s.i_eq_e, 0.0_f64);
}


